Task 8#  Clean code and Eclipse Warnings suppression
j-voting/J-Voting pull request #12
Opened 2019-05-18 01:26 UTC by ErnestBidouille

Changes :
- Clean code in files and supress Eclipse warnings
- README -> Add DONE to task 8#

2019-05-19 14:46 UTC, oliviercailloux commented
Il faut apparemment encore « bidouiller » pour que GitHub mette à jour le diff.

2019-05-19 14:47 UTC, ErnestBidouille commented
@oliviercailloux vous pouvez checker

2019-05-19 16:11 UTC, oliviercailloux requested changes

2019-05-19 16:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/Alternative.java
> -                    .getLogger(Alternative.class.getName());
Mieux vaudrait des @suppressWarnings que enlever et ajouter les loggers chaque fois qu’on en a besoin ou pas. (Cf. cours sur les loggers.)

2019-05-19 16:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/Preference.java
> +    protected List<Set<Alternative>> preferenceid;
Je ne trouve pas ce nouveau nom plus clair. Ce n’est pas un id. Et la convention demanderait `preferenceId`. Il faudrait plutôt nommer cette chose `bestFirstEquivalenceClasses` par exemple (s’il est effectivement tel que la meilleure classe d’alternatives est en premier).

2019-05-19 16:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/analysis/Dictator.java
> +    private Voter dictatorname;
C’était mieux avant. Cette variable ne contient pas le nom du dictateur, mais représente le dictateur lui-même (un électeur).

2019-05-19 16:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/gui/MainGUI.java
> +        if (fileToRead.equals("")) {
Êtes-vous sûr que `fileToRead` ne peut pas être `null` ici ? `Objects.equals()` m’aurait paru plus prudent.

2019-05-19 16:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadProfile.java
> +                if (altText != null && !altText.equals("")) {
Utiliser `!Objects.equals`

2019-05-19 16:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/SWFCommander.java
> +        LOGGER.info(("Enter a StrictPreference complete"));
L’objectif ici est d’interagir avec l’utilisateur via le terminal. Sysout est donc adéquat.

2019-05-21 14:50 UTC, ErnestBidouille commented
Corrigé colme demandé

2019-05-21 14:50 UTC, merged