Task 12# ODSProfile
j-voting/J-Voting pull request #14
Opened 2019-05-19 20:01 UTC by ErnestBidouille

Changes :
- Added ReadODS class that reads and then displays the content (Number of voters, alternatives, etc.) of an ods file.
It is functional but will be improved later on, especially in terms of prints, contracts and Javadoc.

A member of the team did absolutely nothing during this period and we had to review our requirements to get into time...

2019-05-21 14:08 UTC, oliviercailloux commented
Mon exigence de baser les PR sur master ne fonctionne pas bien dans le cas de tâches multiples concurrentes (comme ici). Veuillez SVP modifier cette PR pour la baser sur un départ qui me permet de voir uniquement les différences pertinentes à cette tâche. (Au besoin créer une ou deux branches ad-hoc pour ce faire.)

À faire rapidement SVP pour que je puisse corriger rapidement.

2019-05-21 15:13 UTC, ErnestBidouille commented
@oliviercailloux vous pouvez checker

2019-05-22 11:37 UTC, oliviercailloux requested changes
À poursuivre, et privilégier un format avec les préférences en colonnes, une (ou plusieurs) colonnes par électeur comme discuté.

2019-05-22 11:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +    public static void readSpreadsheetDocument(String file) throws Exception {
Pas grave à ce stade de brouillon, mais pour le futur : entrée devrait être un InputStream, plus général. L’implémentation actuelle ne peut lire que des fichiers dans le class path.
Il faut j’imagine fermer le document quand on a fini avec lui.

2019-05-22 13:12 UTC, ErnestBidouille commented
@j-voting/melta-jvoting Fermeture de la PR les changements seront fait sur une nouvelle branche. Celle-ci n'a plus lieu d'être

2019-05-22 13:12 UTC, closed without merging