Update new diagram for preferences interfaces
j-voting/J-Voting pull request #17
Opened 2019-05-24 14:32 UTC by BoBeauf

Update of preference interface diagram.

2019-05-26 10:40 UTC, oliviercailloux requested changes
On y est presque.
- Voter doit être visible (préfixe +)
- size est ambigu (commenté précédemment je pense)
- je ne comprends toujours pas `getPreferences` sur `Preference` (cf. commentaire précédent)
- source ? (cf. préc)
- je ne trouve pas les méthodes de conversion (`toStrictPreference`) utiles dans l’interface car cette conversion sera généralement impossible ; elles seront éventuellement implémentées à l’extérieur des classes en question si utiles dans certains cas
- `MutableASPreference` ne peut pas étendre `MutablePreference` (erreur possible de ma part), car le second permet l’ajout de paires ex-æquo, le premier l’interdit et ne peut donc pas respecter le contrat. Ajouter les méthodes `addAlternative` et `addStrictPreference(a1, a2)` dans `MASP` pour permettre la modification (`asGraph` muable ne serait pas parfaitement adéquat ici car on ne peut pas ajouter les arcs qu’on veut).
- `CompletePreference` implémente `ImmutablePreference`, comme l’indique votre commentaire (mais pas le diagramme)
- `CompletePreference#getAlternative(position)` devrait être `CompletePreference#getAlternatives(rank)`
- `asEquivalentClasses` devrait être `asEquivalenceClasses`, car ce sont des classes d’équivalence et non des classes équivalentes

2019-05-26 16:05 UTC, oliviercailloux requested changes
(Suite PR #15)
- Votre diagramme (et son code source) n’a rien à faire dans votre class path, vous n’allez jamais l’ouvrir avec votre code, il était très bien dans votre répertoire doc.
- `getAlternatives`, pas `getAlternative`.
- Enlevez `size()`, `getAlternatives().size()` fera tout aussi bien l’affaire et n’est pas ambigu.
- `addAlternative` sur un objet immuable ?
- Votre fichier .txt représentant apparemment le code source du diagramme n’est pas un fichier texte et est visiblement beaucoup trop court pour représenter effectivement le source de ce diagramme. Avez-vous compris ma demande ?

2019-05-28 07:22 UTC, oliviercailloux approved these changes
Great.

2019-05-30 15:04 UTC, BoBeauf commented
Added a public getVoter() method to comply with POO conventions: to avoid direct public access to an attribute, we prefer to use a getter.

2019-05-31 17:30 UTC, oliviercailloux commented
Pas d’accord, l’attribut `voter` indique bien et de façon concise que la préférence est associée à un électeur, attribut conceptuel de la classe. Effectivement, il faut l’implémenter dans un langage OO par une méthode qui s’appellera `getVoter()`, mais c’est un détail d’implémentation.

2019-05-31 17:52 UTC, oliviercailloux commented
Au passage, il y a une erreur que je n’avais pas repérée précédemment sur le diagramme : `Preference#getAlternatives()` doit renvoyer un `Set`, qui n’est un `ImmutableSet` que sur les structures immuables. Et `CompletePreference#asEquivalenceClasses()` devrait renvoyer `ImmutableList<ImmutableSet<Alternative>>`.

2019-06-04 16:32 UTC, oliviercailloux commented
Le diagramme n’apparait plus dans les modifications de cette PR.

2019-06-04 16:36 UTC, BoBeauf commented
@oliviercailloux we need re-review to merge and close iteration 2.

2019-06-04 16:53 UTC, mloubet commented
There was a mistake during last push. Here is the diagram.

2019-06-05 07:25 UTC, oliviercailloux approved these changes
J’imagine qu’on est bon.

2019-06-05 07:39 UTC, merged