Interfaces1
j-voting/J-Voting pull request #18
Opened 2019-05-26 10:04 UTC by BoBeauf

- Change _StrictCompletePreferenceImpl__ in _LinearPreferenceImpl_
- Add 8 interfaces

2019-05-26 13:10 UTC, oliviercailloux requested changes
- Veuillez prendre en compte mes remarques récentes sur le diagramme de classes.
- ECL
- Javadoc sur les interfaces, pas dedans (visible de l’extérieur)
- Le voter associé à la préférence doit être accessible, il faut un `getVoter(): Voter`.

2019-05-27 18:16 UTC, BoBeauf commented
We have modified according to your advice.
However, we have no Warning from Eclipse and do not understand ECL. Can you give us the warning you get ?

2019-05-28 08:46 UTC, oliviercailloux commented
Please see page Projets.adoc and the link therein.

2019-05-30 15:18 UTC, BoBeauf commented
We have modified according to your advice and there is no more Eclipse warning.

2019-05-31 17:45 UTC, oliviercailloux commented
Il y a trop de modifications à la fois ici, on ne s’en sortira jamais. Veuillez introduire une PR spécifique seulement pour l’ajout des huit interfaces.

2019-06-04 16:20 UTC, BoBeauf commented
Change PR to "add 8 interfaces".

2019-06-04 16:20 UTC, closed without merging