Task 1# and 2#
j-voting/J-Voting pull request #22
Opened 2019-05-30 22:40 UTC by ErnestBidouille

Done : 
- 1#  ODSProfile : clear code 
- 2#  ODSProfile : add 2 new format types of .ODS

2019-06-01 08:40 UTC, oliviercailloux requested changes
DRY. Un seul exemplaire de `facon1.ods`, etc.
Indiquer dans votre `README` ou un document spécifique dans Doc une brève documentation avec des liens vers vos exemples (`facon1`, etc.) et qqs explications succinctes. Les exemples se se suffisent pas entièrement à eux-mêmes : on ne peut pas deviner où sont les électeurs, les alternatives, les rangs…
Renommer `facon1`, `facon2` etc. avec un nom qui indique le format choisi. Essayez de trouver des noms descriptifs et courts. Utiliser si opportun le terme "strict" pour "sans ex-æquo".

2019-06-01 08:40 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +        LOGGER.debug(inputStream.toString());
Ceci n’affiche pas grand-chose d’utile. L’avez-vous testé ?

2019-06-01 08:40 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +        if (Objects.equals(table, null))
Utiliser `requireNonNull`

2019-06-01 08:40 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +                                            .getStringValue())));
Rendre ce code plus lisible : affecter les résultats intermédiaires à des variables.

2019-06-01 18:18 UTC, ErnestBidouille commented
@oliviercailloux Le document spécifique explicatif est déjà créé c.f. PR #21 et sera joint sur la branche master dès les merges réalisées

2019-06-02 19:42 UTC, oliviercailloux approved these changes

2019-06-03 11:02 UTC, merged