Task 7#  ODSProfileTest : Junit tests for ODSProfile
j-voting/J-Voting pull request #23
Opened 2019-05-30 22:43 UTC by ErnestBidouille

Done :
- Junit tests for ReadODS.java

2019-06-01 08:43 UTC, oliviercailloux requested changes

2019-06-01 08:43 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
> +        inputStream1 = ReadODS.class.getResourceAsStream("./testods.ods");
Enlever `./`

2019-06-01 08:43 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
> +        assertTrue(Objects.equal(stringCompare1, stringrReadODS));
`assertEquals`

2019-06-02 20:22 UTC, oliviercailloux approved these changes
Cette PR ne sera approuvée officiellement (c-à-d à fusionner) qu’après approbation de la tâche ReadODS, puisqu’elle en dépend. Il faut encore effacer les fichiers de Doc, qui font double emploi.

2019-06-02 20:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +    @RequiresNonNull("table")
Avez-vous testé votre code ? Ceci n’aura aucun effet, j’imagine. Utiliser `Objects.requireNonNull`.

2019-06-02 21:59 UTC, ErnestBidouille commented
> Cette PR ne sera approuvée officiellement (c-à-d à fusionner) qu’après approbation de la tâche ReadODS, puisqu’elle en dépend. Il faut encore effacer les fichiers de Doc, qui font double emploi.

Ils font double emploi mais on augmente ici la lisibilité et l'accessibilité de ces fichiers aux formats assez spéciaux étant donné le document explicatif qui sera present. @oliviercailloux

2019-06-03 10:50 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +    @RequiresNonNull("table")
Je trouvais cela bizarre aussi...

2019-06-03 11:10 UTC, merged

2019-06-04 09:59 UTC, oliviercailloux commented
En utilisant des liens vers un seul exemplaire de chaque fichier, vous obtenez à peu près tous les bénéfices sans les inconvénients.