Tasks Complete preference
j-voting/J-Voting pull request #30
Opened 2019-06-17 15:46 UTC by ErnestBidouille

Done : 
- CompletePreferenceImpl class done

Minor corrections in Interface

2019-06-17 16:26 UTC, oliviercailloux requested changes
ECL
Fusionner avec le PR changeant les interfaces pour m’éviter de voir les modifications à l’interface.
Inclure les tests unitaires, y compris pour tester le cas d’alternatives dupliquées dans plusieurs classes d’équivalence (devrait être refusé) et le cas liste vide (accepté) et le cas liste contenant un ensemble vide (à refuser et à documenter).

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +import javax.ws.rs.NotFoundException;
N’a pas sa place ici, exception associée aux web services REST.

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +    Voter voter;
private

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +     * @param preference : <code> not null </code>
pas de :

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +    public static CompletePreferenceImpl createCompletePreferenceImpl(
Nom : `asCompletePreference`. Renvoyer un `CompletePreference`, l’appelant n’a pas à savoir de quelle classe il s’agit exactement.

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +                    Voter voter) {
Il me semble plus naturel d’inverser ces paramètres. Nommer l’un `equivalenceClasses` et préciser dans la doc que la meilleure classe d’équivalence doit être en premier.

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        for (ImmutableSet<Alternative> set : preference) {
`equivalenceClass: equivalenceClasses`

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +                if (!Objects.isNull(lastSetLinker)) {
Inutilement compliqué à lire. `lastSetLinker != null` est plus simple.

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        System.out.println(Graphs.transitiveClosure(newGraph).toString());
Non, utiliser un LOGGER.

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        }
Attention, dans la logique adoptée maintenant, le graphe renvoyé est censé être transitif, ce qui n’est pas le cas actuellement.

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        throw new NotFoundException("Alternative not found");
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/NoSuchElementException.html

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        Preconditions.checkArgument(rank > 0);
Asymétrie bizarre entre rang trop petit et rang trop grand (non vérifié explicitement). Mieux vaut laisser l’exception par défaut à mon avis (out of range).

2019-06-17 16:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +    private ImmutableGraph<Alternative> createGraph(
Être un peu plus tolérant dans les paramètres acceptés serait sympathique. Une `List` suffit. (À transformer en ImmutableList en interne). Et le paramètre de la liste devrait être `? extends Set<Alternative>` (à transformer).

2019-06-17 16:45 UTC, ErnestBidouille commented
Les tests sont sur une deuxieme PR

2019-06-17 16:47 UTC, ErnestBidouille commented
@oliviercailloux les tests sont dans une autre PR

2019-06-17 17:07 UTC, oliviercailloux requested changes
Mauvaise idée, mettez les tests dans la même PR SVP. Je ne peux pas m’assurer de la qualité du code sans les tests.

2019-06-17 18:07 UTC, ErnestBidouille commented
@oliviercailloux tests ajoutés, je pense que la couverture de ceux-ci est correcte

2019-06-17 20:32 UTC, oliviercailloux requested changes
Il me semble que beaucoup de mes commentaires n’ont pas été pris en compte. Vérifiez systématiquement (nouveaux et anciens commentaires) SVP.

2019-06-17 20:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +    private CompletePreferenceImpl(
- Changer l’ordre par cohérence
- Paramètre plus large
- Nommé `equivalenceClasses`

2019-06-17 20:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +    public static CompletePreferenceImpl asCompletePreference(Voter voter,
- Paramètre plus large (`List<?…`).
- Renvoyer un `CompletePreference`, l’appelant n’a pas à savoir de quelle classe il s’agit exactement.

2019-06-17 20:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        for (Set<Alternative> set : preference) {
`equivalenceClass : equivalenceClasses` (pour code plus lisible)

2019-06-17 20:40 UTC, ErnestBidouille commented
@oliviercailloux les commentaires étaient pris ne compte. Ceux-ci sont nouveaux

2019-06-17 21:24 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        return (ImmutableList<ImmutableSet<Alternative>>) equivalenceClasses;
Le cast était obligatoire afin de respecter l'interface et le diagramme de classes

2019-06-17 21:38 UTC, oliviercailloux commented
> @oliviercailloux les commentaires étaient pris en compte. Ceux-ci sont nouveaux

Non, par exemple le commentaire « Renvoyer un CompletePreference, l’appelant n’a pas à savoir de quelle classe il s’agit exactement. » existait déjà et n’avait pas été pris en compte.

2019-06-17 21:40 UTC, ErnestBidouille commented
@oliviercailloux il avait été pris en compte pour la fonction, où le commentaire était, pas les autres je suis d'accord.

2019-06-18 08:55 UTC, ErnestBidouille commented
@oliviercailloux qu'en pensez-vous maintenant ?

2019-06-18 11:17 UTC, oliviercailloux requested changes
Un test existe-t-il pour le cas où une alternative est dupliquée dans deux classes d’équivalence ? Je ne le vois pas.

2019-06-18 11:17 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +    private ImmutableList<? extends Set<Alternative>> equivalenceClasses;
Ceci doit être une `ImmutableList<ImmutableSet<…`, pour satisfaire le contrat.

2019-06-18 11:17 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        return (ImmutableList<ImmutableSet<Alternative>>) equivalenceClasses;
Le cast ne suffit pas à respecter l’interface. Il échouera si les types ne sont pas convertibles. Il faut copier les ensembles dans des `ImmutableSet` au moment de la réception.

2019-06-18 11:17 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +        }
Utiliser assertThrows, beaucoup plus clair.

2019-06-18 11:17 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +        ImmutableSet<Alternative> immutableSet = ImmutableSet.copyOf(set);
Utiliser le constructeur approprié pour créer l’ensemble en une seule ligne sans ensemble intermédiaire inutile. Même chose pour la liste.

2019-06-18 11:17 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +    @BeforeAll
Structure injustifiée car de nombreux tests n’utilisent pas cette préparation. Procédez sans cette annotation (en appelant la méthode là où nécessaire). Il serait également plus clair de faire renvoyer la préférence construite par la méthode.

2019-06-18 11:17 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +        assertEquals("isDirected: true, allowsSelfLoops: true, nodes: [1, 2, 3], edges: [<1 -> 1>, <1 -> 2>, <1 -> 3>, <2 -> 1>, <2 -> 2>, <2 -> 3>, <3 -> 3>]",
Je supprimerais ce test. On peut changer la représentation `toString()`, elle n’est pas associée à un contrat précis.

2019-06-18 11:24 UTC, ErnestBidouille commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +    @BeforeAll
@oliviercailloux J'ai utilisé BeforeAll et non BeforeEach dans cette optique

2019-06-18 12:33 UTC, ErnestBidouille commented
@oliviercailloux je pense que maintenant, le code est bon.

2019-06-18 14:36 UTC, oliviercailloux requested changes
Il faut fusionner d’abord la nouvelle version de l’interface dans master, pour que les changements n’apparaissent plus ici.

Je ne vois toujours pas le test dont je parlais dans mon commentaire précédent.

2019-06-18 14:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        List<ImmutableSet<Alternative>> listImmutableSets = new ArrayList<>();
Il serait plus élégant d’utiliser un builder, comme recommandé par Guava, pour construire la liste.

2019-06-18 14:36 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +    private CompletePreference ifNeededByTest() {
`getTwoClassesPreference`, par exemple, serait nettement plus descriptif.

2019-06-18 14:36 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +        assertEquals("[1, 2]", toTest.getAlternatives(1).toString());
Éviter de tester les représentations toString. Le test qui suit couvre suffisamment la fct.

2019-06-18 14:36 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +        list.add(immutableSet2);
Construire la liste en une seule ligne avec le constructeur ad hoc.

2019-06-18 14:36 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImplTest.java
> +        ImmutableSet<Alternative> immutableSet = ImmutableSet
C’est un détail, mais tant qu’on y est : `set12` par exemple serait plus clair. (Et `set3` pour l’ensemble suivant.)

2019-06-18 14:38 UTC, ErnestBidouille commented
@oliviercailloux les tests de duplication et empty sont là

2019-06-18 15:02 UTC, ErnestBidouille commented
@oliviercailloux je pense que nous sommes en phase pour cette PR

2019-06-18 15:12 UTC, ErnestBidouille commented
> Il faut fusionner d’abord la nouvelle version de l’interface dans master, pour que les changements n’apparaissent plus ici.

La fusion est faite mais le git diff ne se met pas bien à jour...

2019-06-18 16:37 UTC, ErnestBidouille commented
> 
> 
> @oliviercailloux les tests de duplication et empty sont là



> 
> 
> > Il faut fusionner d’abord la nouvelle version de l’interface dans master, pour que les changements n’apparaissent plus ici.
> 
> La fusion est faite mais le git diff ne se met pas bien à jour...



> 
> 
> > Il faut fusionner d’abord la nouvelle version de l’interface dans master, pour que les changements n’apparaissent plus ici.
> 
> La fusion est faite mais le git diff ne se met pas bien à jour...

2019-06-19 11:54 UTC, ErnestBidouille commented
@oliviercailloux pouvez-vous valider cette PR ?

2019-06-19 12:12 UTC, oliviercailloux requested changes

2019-06-19 12:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +     * @throws EmptySetException       if a Set is empty
L’idée en général est bonne, mais en l’occurence, ces exceptions sont inutilement détaillées. Il y a très peu de chances que votre client se soucie de la nature exacte d’une erreur, si elle survient. Si on veut être cohérent dans un tel souci du détail des erreurs, on va se retrouver avec des centaines d’exceptions différentes pour chaque sous cas envisageable. 

Enlevez ces deux exceptions et renvoyez simplement IllegalArgumentException. Indiquez ces restrictions dans la Javadoc au niveau du paramètre `equivalenceClasses`.

2019-06-19 12:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        List<ImmutableSet<Alternative>> listImmutableSets = Lists
Je ne comprends pas. J’ai commenté précédemment ici en demandant d’utiliser le builder de Guava pour construire la liste, et vous avez marqué la conversation comme Resolved, mais je ne vois pas de changement.

2019-06-19 12:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        }
Toutes ces vérifications devraient être faites dans le constructeur de la classe.

2019-06-19 12:12 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        return ImmutableSet.copyOf(returnedSet);
Il ne faut pas recalculer cet ensemble chaque fois que cette méthode est appelée ! Seulement une fois, lors de la construction.

2019-06-19 12:33 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        List<ImmutableSet<Alternative>> listImmutableSets = Lists
@oliviercailloux je n'y arrive pas. en effet, caster du <? extends Set> en Immutable set dans le Builder n'est pas chose aisée. Je trouve que la méthode actuelle est claire non ?

2019-06-19 12:35 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +     * @throws EmptySetException       if a Set is empty
J'aimerai les laisser. elles sont intéressantes et pourront être réutilisées par la suite. Ces deux Exceptions sont très spécifiques et permettent d'obtenir une information claire sur la non duplication et les cas de Set empty

2019-06-19 12:35 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        List<ImmutableSet<Alternative>> listImmutableSets = Lists
De plus j'avais pensé que Lists.newArrayList correspondait

2019-06-19 12:39 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        }
@oliviercailloux pourquoi pas, mais le changement n'est pas nécessaire au bon fonctionnement je trouve

2019-06-19 12:43 UTC, ErnestBidouille commented
@oliviercailloux Je pense que nous sommes bon pour cette PR, non ?

2019-06-19 12:44 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        }
DONE

2019-06-19 15:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +     * @throws EmptySetException       if a Set is empty
Je ne suis pas convaincu. Si un problème se produit, il sera dû à une erreur de programmation de la part du client. Une telle erreur devrait être relativement rare. Et si elle survient, votre message dans l’exception sera tout aussi clair que le type de l’exception. Je ne vois donc pas l’intérêt d’un type spécifique. Un client n’écrira jamais du code visant à capturer une exception spécifique, il devra plutôt corriger le bug s’il en trouve un.

2019-06-19 15:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        List<ImmutableSet<Alternative>> listImmutableSets = Lists
La méthode actuelle est claire mais n’est pas la meilleure manière de procéder : le builder est optimisé pour construire une `ImmutableList`, et est un idiôme à adopter par habitude pour toute construction de liste (même si ici ce n’est pas crucial). 

Abandonnons ceci, si vous ne voyez pas comment faire.

2019-06-19 15:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        }
Sinon, il va être difficile de récupérer le travail de construction de l’ensemble des alternatives.

2019-06-19 15:37 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        List<ImmutableSet<Alternative>> listImmutableSets = Lists
Je peux le faire si je change <? extends Set> en Set uniquement

2019-06-19 15:37 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        List<ImmutableSet<Alternative>> listImmutableSets = Lists
Ce qui n'est pas optimal

2019-06-19 15:42 UTC, oliviercailloux requested changes

2019-06-19 15:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +                        ImmutableList.copyOf(equivalenceClasses));
C’est un détail, mais passer ici simplement `equivalenceClasses` serait plus clair (chacun son boulot, la construction de la liste immuable sera faite par le constructeur).

2019-06-19 15:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +        return ImmutableSet.copyOf(graph.nodes());
Votre implémentation de `getAlternatives()` est en O(n). Pas terrible, sachant qu’en changeant qqs lignes de code, vous obtenez une implémentation en O(1). Mémorisez une fois pour toutes l’ensemble des alternatives, que vous calculez de toute façon dans le constructeur !

2019-06-19 15:58 UTC, ErnestBidouille commented
@oliviercailloux cette fois, je pense que c'est bon

2019-06-19 16:59 UTC, oliviercailloux approved these changes
Je vois que les exceptions dont nous avons discuté sont toujours présentes, et ce n’est pas très important, donc fusion acceptée à ce stade. Cependant, vous auriez dû répondre à mon commentaire, s’il a soulevé une objection dans votre esprit.

2019-06-19 17:01 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/CompletePreferenceImpl.java
> +     * @throws EmptySetException       if a Set is empty
Je pensais avoir répondu. Pouvons nous en parler au prochain cours ? Ce sera plus simple je pense

2019-06-19 17:01 UTC, ErnestBidouille commented
> Je vois que les exceptions dont nous avons discuté sont toujours présentes, et ce n’est pas très important, donc fusion acceptée à ce stade. Cependant, vous auriez dû répondre à mon commentaire, s’il a soulevé une objection dans votre esprit.

@oliviercailloux Je pensais avoir répondu. Pouvons nous en parler au prochain cours ? Ce sera plus simple je pense

2019-06-19 17:05 UTC, oliviercailloux commented
> @oliviercailloux Je pensais avoir répondu. Pouvons nous en parler au prochain cours ? Ce sera plus simple je pense

Bien sûr.

2019-06-19 19:40 UTC, merged