Task LinearPreference
j-voting/J-Voting pull request #33
Opened 2019-06-18 13:27 UTC by ErnestBidouille

Done :
- Implemented LinearPrefrence & Tests

@oliviercailloux pour le moment le git diff est fait par rapport à completePref pour cacher les classes non concernées par la PR. Dès que la PR de completePref sera mergée, le git diff sera fait sur master

2019-06-18 13:45 UTC, ErnestBidouille commented
@oliviercailloux le git diff met en avant des différences qui n'existent pas ! A faire attention. CompletePreferenceImpl.java est exactement identique sur les deux branches, l'erreur vient de GitHub

2019-06-18 18:23 UTC, ErnestBidouille commented
> 
> 
> @oliviercailloux le git diff met en avant des différences qui n'existent pas ! A faire attention. CompletePreferenceImpl.java est exactement identique sur les deux branches, l'erreur vient de GitHub. Ne regardez que les nouvelles classes -> LinearPreferenceImpl.java et LinearPreferenceImplTest.java

2019-06-18 18:25 UTC, ErnestBidouille commented
L'erreur semble corrigée

2019-06-19 11:30 UTC, oliviercailloux requested changes
Réutilisez plutôt CompletePreference, pour éviter de re-tester et dupliquer éventuellement les bugs. LP construit initialement une instance de CP en interne et délègue les appels à CP. (Pattern delegate.) Il suffit de vérifier que les classes d’équivalence sont des singletons.

2019-06-19 11:38 UTC, ErnestBidouille commented
@oliviercailloux je ne comprends pas

2019-06-26 21:00 UTC, closed without merging