Mutable preference class
j-voting/J-Voting pull request #34
Opened 2019-06-18 22:32 UTC by anaeldray

The mutablePreferenceClass' implementation.
preferencesClassesMain is only temporary, we will implement unit tests ASAP.

2019-06-19 15:22 UTC, oliviercailloux requested changes
FORMAT

Votre implémentation actuelle ne garantit pas de conserver le graphe fermé transitivement : par exemple, `asGraph().putEdge()` ne recalcule pas la fermeture transitive.

On peut contourner ce problème en modifiant légèrement les contrats. Ajoutez dans l’interface `MutablePreference` une méthode `asMutableGraph()`, documentez que ce graphe n’est pas nécessairement transitivement fermé ni nécessairement réflexif, et ajoutez « TODO : should forbid removing alternatives from the set of nodes (surprising results when a > b > c and removing b as it might disconnect the graph) ». Supprimez la particularisation de `asGraph()` de `MutablePreference`, pour revenir au contrat de `Preference` (à savoir un graphe non modifiable, transitivement fermé, réflexif). Documentez « The returned graph can’t be modified, though is not necessarily immutable ». Pour faire simple pour commencer, vous pouvez recalculer la fermeture transitive à chaque appel (on peut faire mieux plus tard mais faire beaucoup mieux n’est pas simple). Mettez le diagramme à jour également. Tant que vous y êtes, enlevez l’héritage entre `MutableASPreference` et `MutablePreference`, c’est une erreur (il est impossible de satisfaire le contrat général de mutabilité de `MutablePreference` dans `MutableASPreference` puisque ce dernier est plus restrictif).

Pour revenir à votre implémentation, ne maintenez donc pas du tout votre graphe modifiable transitivement fermé : autant le faire pas du tout qu’à moitié.

Certains constructeurs proposés sont compliqués et me semblent peu utiles. Par contre il est utile de pouvoir proposer un graphe de départ. Prévoyez SVP simplement deux constructeurs statiques, `given(voter, preference: Graph)` et `given(preference: Graph)` et un constructeur interne (privé) `MutablePreferenceImpl(voter, preference)`.

2019-06-19 15:22 UTC, oliviercailloux commented on pom.xml
> +		</dependency>
Je ne pense pas que vous ayez besoin d’un autre ensemble de collections. Contentez-vous de celles de la JDK et de Guava. Ou dites-moi pourquoi vous en avez l’usage.

2019-06-19 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +                    Voter voter) {
Votre retour à la ligne est très bizarre. Pourquoi le deuxième paramètre ne rentre pas sur la ligne, alors que le commentaire juste en-dessous est mis en page sur une longueur de ligne largement assez longue pour permettre d’avoir les deux paramètres sur la même ligne ?

2019-06-19 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +     * Those datas are implemented in a graph.
Il ne faut pas préciser l’implémentation, cela ne fait pas partie du contrat public.

2019-06-19 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +     */
Supprimer ce commentaire et regarder le résultat.

2019-06-19 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +    public void addExAequo(Alternative a1, Alternative a2) {
`addEquivalence`

2019-06-19 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +    public void addStrictPreference(Alternative a1, Alternative a2) {
Ce nom peut induire en erreur. S’il y a déjà un lien a2 ≥ a1, cet appel n’ajoute pas une préférence stricte mais une équivalence. Je nommerais simplement `putEdge`.
La doc devrait mentionner a1 ≥ a2 plutôt que a1 > a2. La préférence sera considérée comme stricte seulement si la paire (a2, a1) n’est pas présente dans le graphe.

2019-06-19 15:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +    @Override public Set<Alternative> getAlternatives() {
Réfléchissez au respect du contrat par votre implémentation. Cela peut être compliqué de l’implémenter correctement, auquel cas, indiquez par un TODO dans la javadoc de cette méthode ce qui reste à faire pour bien satisfaire le contrat.

2019-06-19 15:27 UTC, oliviercailloux requested changes
… et qqs restes.

2019-06-19 15:27 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +	public Set<List<Set<Alternative>>> asSetlistSet() {
Supprimez cette méthode. Je doute qu’il existe une implémentation raisonnable de ce concept, mais si vous en avez une en tête, on peut toujours en discuter quand vous serez prêts à l’implémenter.

2019-06-19 15:27 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/MutablePreferenceImplTest.java
> +        MutableGraph G = pref.asGraph();
petit g

2019-06-19 15:27 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +		return asGraph().toString() + "\n" + voter.toString();
Utiliser Guava comme vu au cours.

2019-06-20 09:17 UTC, oliviercailloux requested changes
Mettez le diagramme à jour SVP, sinon des grosses confusions vont s’ensuivre !

« Tant que vous y êtes, enlevez l’héritage entre MutableASPreference et MutablePreference, c’est une erreur (il est impossible de satisfaire le contrat général de mutabilité de MutablePreference dans MutableASPreference puisque ce dernier est plus restrictif). »

Ne maintenez pas votre graphe interne transitivement fermé (supprimez les fermetures transitives à chaque modification). Calculez la fermeture transitive sur la copie que vous renvoyez quand vous répondez à `asGraph()`. Ou, à votre choix, maintenez deux copies en interne du graphe : le graphe "réduit" et le graphe fermé transitivement.

On peut en parler en séance si l’objectif n’est pas clair.

2019-06-20 09:17 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutablePreference.java
> +	public ImmutableGraph<Alternative> asGraph();
“is not necessarily immutable”, dit la doc, donc renvoyer `Graph` et pas `ImmutableGraph` !

Il faut supprimer cette méthode de cette interface et déplacer cette documentation sur `Preference#asGraph()`.

2019-06-20 09:17 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutablePreference.java
> +	 * @see MutablePreference#asGraph() TODO : should forbid removing alternatives
Le TODO devrait être au niveau de la documentation générale, pas au niveau du `@see`.

2019-06-20 09:17 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +		return Graphs.copyOf(graph);
Renvoyer le graphe lui-même. L’idée est de permettre au client de modifier le graphe de préférence directement.

2019-06-26 21:01 UTC, closed without merging

2019-06-30 09:01 UTC, oliviercailloux reviewed
Dites-moi SVP ce qui a changé dans le diagramme, je ne vois pas.

La méthode `asGraph()` devrait retourner un graphe qui reflète à tout moment la préférence, pas une copie immuable. Mais à ce stade j’accepte cette PR en l’état. Fusionner après éventuelles adaptations mineures comme demandé.

2019-06-30 09:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/MutablePreferenceImpl.java
> +	public static MutablePreferenceImpl given(MutableGraph<Alternative> pref, Voter voter) {
`Voter` d’abord, par cohérence (vérifier systématiquement).

2019-06-30 09:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/preferencesClassesMain.java
> +public class preferencesClassesMain {
Qu’est-ce ?

2019-06-30 09:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutablePreference.java
> +	 * @see MutablePreference#asGraph() TODO : should forbid removing alternative
Référence à soi-même ?

2019-06-30 09:17 UTC, emiliechhean commented
@oliviercailloux @anaeldray Cette Pull Request n'est plus à jour, elle a été fermée il y a 4 jours. La bonne Pull Request associée à la classe MutablePreference et ses tests correspondants se nomme Mutable preference it 4.