Instanciate CompletePref with ReadODS
j-voting/J-Voting pull request #35
Opened 2019-06-19 00:38 UTC by ErnestBidouille

Done :
- petits changements sur ReadODS
- Instanciation de la class CompletePreferenceImpl
- Ajout des tests liés sur READODSTests

2019-06-19 14:01 UTC, oliviercailloux requested changes
On ne doit plus être très loin de pouvoir finaliser et fusionner CompletePref, dont cette tâche dépend. Redemandez la review après fusion SVP.

2019-06-19 17:06 UTC, ErnestBidouille commented
Vous pouvez conciderer que completePref est merge

2019-06-20 08:49 UTC, oliviercailloux requested changes
Pourriez-vous pour commencer mettre en conformité les noms des formats, dans le code et dans les noms des fichiers tests, pour qu’ils correspondent à votre [doc](https://github.com/j-voting/J-Voting/blob/master/Doc/votingFilesFormatsDoc.adoc), pour que je m’y retrouve ?

Pourquoi ne pas fusionner CompletePreference ? On y verrait plus clair.

2019-06-20 10:14 UTC, ErnestBidouille commented
@oliviercailloux  CompletePref est fusionnée déja avec master
Les noms des fichiers de tests sont exactement les mêmes avec "complete_" rajouté devant pour me faciliter les tests (les fichiers sont plus petits)

2019-06-20 10:26 UTC, ErnestBidouille commented
@oliviercailloux  J'ai modifié le nom des fichiers pour qu'ils soient plus parlant ainsi que la doc

2019-06-20 14:15 UTC, oliviercailloux requested changes
SVP modifier code pour conformité aux noms de formats documentés, comme demandé

2019-06-20 15:11 UTC, ErnestBidouille commented
@oliviercailloux les noms sont exactement les mêmes. C'est juste une version "light" des fichiers pour éviter de créer des tests énormes. rank_format.ods et rank_format_reduced.ods sont présents dans la doc et rank_format_reduced.ods n'est qu'un version réduite de rank_format.ods

2019-06-20 15:14 UTC, ErnestBidouille commented
> 
> 
> SVP modifier code pour conformité aux noms de formats documentés, comme demandé



@oliviercailloux les noms sont les mêmes. C'est juste une version "light" des fichiers pour éviter de créer des tests énormes. rank_format.ods et rank_format_reduced.ods sont présents dans la doc et rank_format_reduced.ods n'est qu'une version réduite de rank_format.ods. Cela ne change en rien la lisibilité du code.
Pouvez-vous faire une review là dessus et venir m'en parler demain si vous ne comprenez pas ?

2019-06-20 18:03 UTC, oliviercailloux requested changes

2019-06-20 18:03 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
>      public static String printFormatLikeSOC(Table table) {
Qu’est-ce que le format "like SOC" ?

2019-06-20 18:15 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
>      public static String printFormatLikeSOC(Table table) {
@oliviercailloux il correspond au format de "election_data_format.ods". Cette partie du code avait déjà été validée pas vos soins lors d'une PR antérieure.

2019-06-20 19:06 UTC, oliviercailloux requested changes

2019-06-20 19:06 UTC, oliviercailloux commented on Doc/votingFilesFormatsDoc.adoc
>  Example VotersToRankings format :
Tant que nous y sommes, voudriez-vous corriger le code pour en faire du Asciidoctor correct (qui s’affiche correctement via GitHub) ?

2019-06-20 19:06 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
>      public static String printFormatLikeSOC(Table table) {
Il me semble que j’avais déjà demandé précédemment de renommer ces méthodes de façon à indiquer clairement à quel format elles font référence. Si j’ai fini par valider ce code sans que cela ait été fait, c’est une erreur. Il ne convient pas d’avoir des noms de format dans la doc et des noms complètement différents dans le code, personne ne va s’y retrouver (en tous cas, pas moi).

2019-06-20 19:20 UTC, ErnestBidouille commented on Doc/votingFilesFormatsDoc.adoc
>  Example VotersToRankings format :
Je peux le faire. Je ne me suis pas occupé de cette PR à l'époque

2019-06-20 19:27 UTC, ErnestBidouille commented
> Il me semble que j’avais déjà demandé précédemment de renommer ces méthodes de façon à indiquer clairement à quel format elles font référence. Si j’ai fini par valider ce code sans que cela ait été fait, c’est une erreur. Il ne convient pas d’avoir des noms de format dans la doc et des noms complètement différents dans le code, personne ne va s’y retrouver (en tous cas, pas moi).

Non cela n'avait pas été dit à l'époque, je le ferai ASAP. Pouvez-vous donner un avis sur les fonctions d'implémentation ? Ce sont elles qui m'intéressent vraiment pour le moment

2019-06-20 19:29 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
>      public static String printFormatLikeSOC(Table table) {
Non cela n'avait pas été dit à l'époque, je le ferai ASAP.
 Pouvez-vous donner un avis sur les fonctions d'implémentation ? Ce sont elles qui m'intéressent vraiment pour le moment afin de juger de la qualité du code nouveau

2019-06-21 10:03 UTC, oliviercailloux approved these changes
Modifiez à la marge et ok pour la fusion ensuite.

2019-06-21 10:03 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +            throw new BadFormatODSException("This format is not allowed");
Soyez un poil plus explicite dans le message ! (« Expected data at cell (1, 0) », par exemple.)

2019-06-21 10:03 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +    public static ImmutableSet<CompletePreference> completeFormatVotersToRankings(
Il faut vérifier que les voteurs sont distincts dans l’entrée et renvoyer une exception mentionnant ce problème sinon. En l’état, vous risquez de silencieusement oublier un électeur ou de créer un ensemble de préférences bizarre dans lequel un électeur donné a deux préférences distinctes.

2019-06-21 10:03 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +                list.add(ImmutableSet.of(Alternative.withId(Integer
Détail, mais il aurait été élégant de créer une méthode qui crée une alternative à partir d’une cellule.

2019-06-21 10:03 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
>          assertEquals(stringCompare3, ReadODS.checkFormatandPrint(inputStream3));
Facultatif : modifiez vos tests pour comparer non pas à un string mais aux données attendues (donc comparer à une CP définie statiquement dans le code). Il n’est pas très satisfaisant de dépendre de la façon précise de représenter les rangements. Vous pouvez aussi en faire une tâche distincte (éventuellement à laisser à vos successeurs).

2019-06-21 10:03 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
> +                                        Voter.createVoter(1),
Code très peu lisible. Améliorer la situation avec une méthode `getAlternativeSet(Integer… id)`. Ou créer ces ensembles d’abord (les nommer `a1`, `a24`, …).

2019-06-21 14:12 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODS.java
> +                list.add(ImmutableSet.of(Alternative.withId(Integer
@oliviercailloux C'est fait

2019-06-21 14:21 UTC, ErnestBidouille commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
>          assertEquals(stringCompare3, ReadODS.checkFormatandPrint(inputStream3));
@oliviercailloux étant donné que la fonction appelée ne fait que retourner une String, je pense qu'il n'est pas necessaire de comparer à une CP étant donné qu'aucune CP n'est crée dans la fonction appelée

2019-06-21 14:25 UTC, ErnestBidouille commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
> +                                        Voter.createVoter(1),
@oliviercailloux très dur de creer une fonction polyvalente pour creer des tests comme ceux-ci. Je ne vois pas comment faire

2019-06-21 15:39 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
> +                                        Voter.createVoter(1),
Créer une méthode `getAlternatives(int... ids): ImmutableSet<Alternative>`. Ensuite, créer dans la méthode problématique une variable `ImmutableSet<Alternative> a1 = getAlternatives(1)`, une variable `ImmutableSet<Alternative> a24 = getAlternatives(2, 4)`, et ainsi de suite. Utiliser ces variables dans le code pour le raccourcir. (De même, on peut créer d’abord les électeurs.)

2019-06-21 15:41 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
>          assertEquals(stringCompare3, ReadODS.checkFormatandPrint(inputStream3));
C’est vrai, le problème réel est dans la méthode `checkFormatAndPrint`, cette méthode n’a pas beaucoup de sens car elle renvoie un string. Il faudrait idéalement découpler la construction d’une CP et son affichage.

2019-06-21 15:52 UTC, ErnestBidouille commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
> +                                        Voter.createVoter(1),
@oliviercailloux ah yes, compris !

2019-06-21 15:58 UTC, ErnestBidouille commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
>          assertEquals(stringCompare3, ReadODS.checkFormatandPrint(inputStream3));
@oliviercailloux la fonction checkFormatAndReturnCompletePreference est déjà implémentée pour ce genre de chose je pense

2019-06-21 16:18 UTC, ErnestBidouille commented on src/test/java/io/github/oliviercailloux/j_voting/profiles/management/ReadODSTest.java
> +                                        Voter.createVoter(1),
@oliviercailloux DONE

2019-06-21 16:21 UTC, merged