README for last iteration
j-voting/J-Voting pull request #39
Opened 2019-06-22 18:22 UTC by BoBeauf

2019-06-24 08:35 UTC, oliviercailloux requested changes
Ce plan me semble imprudent. Il faut autant que possible réutiliser une implémentation pour faire une autre, comme discuté en séance (Forwarding pattern), pas implémenter indépendamment. Dès lors, cette liste de tâches est fortement dépendante de l’ordre d’acceptation et admet peut-être peu de travail en parallèle. Cela fonctionnera seulement si vous êtes prêts à travailler régulièrement sur le projet, et surtout pas tous ensemble les deux derniers jours.

Vous pourriez envisager plutôt d’autres tâches plus indépendantes, comme examiner l’impact de la nouvelle structure sur le code et tenter de faire fonctionner le reste du code pré-existant avec la nouvelle structure en vue d’effacer les anciennes classes de préférences. Mais si vous insistez avec ces tâches, je vous laisse faire.

2019-06-24 11:41 UTC, BoBeauf commented
Le plan présente les classes une par une pour savoir exactement où nous en sommes, l'ordre des tâches ne reflète en effet pas l'ordre réel des implémentations.
Nous avons décidé de ne pas intégrer au plan une quelconque examination des impacts de la nouvelle structure sur le code. En effet, le temps restant étant assez court, nous préférons nous concentrer au maximum sur la création des nouvelles classes afin de rendre un logiciel propre. Cependant cette examination sera sûrement effectuée dans la semaine en parallèle des créations, mais nous préférons ne pas affirmer dans la liste des tasks qu'elle sera terminée pour la fin de l'itération. Priorité à la qualité du rendu.
Qu'en pensez-vous ?

2019-06-24 16:02 UTC, oliviercailloux commented
Dans tous les cas, je n’exige pas que vous vous en teniez à la liste annoncée. Elle me sert juste à mettre en garde ou à discuter avec l’équipe lorsque j’entrevois des risques ou qu’elle fait fausse route.

Voilà qui est fait. À vous d’ajuster dynamiquement durant l’itération.

2019-06-29 15:58 UTC, BoBeauf commented
@oliviercailloux nous avons modifié les équipes pour que vous compreniez un peu mieux qui a travaillé sur quoi lors de cette dernière itération : l'équipe Théo/Mattéo s'est divisé en deux équipes d'une personne, ils ont travaillé chacun sur des tâches un peu différentes pour que le projet avance dans les temps.

2019-06-30 14:58 UTC, oliviercailloux approved these changes
Assurez-vous surtout que les personnes affectées sur les tâches et les marqueurs Milestones sont corrects, car c’est cela que j’utilise pour noter.

2019-06-30 15:06 UTC, BoBeauf commented
Pas de soucis à ce niveau là, merci.

2019-06-30 15:24 UTC, merged