ImmutablePreferenceImpl + Tests
j-voting/J-Voting pull request #41
Opened 2019-06-23 14:59 UTC by ErnestBidouille

Done :
- ImmutablePreference + Tests

Les tests vont changer, je pense qu'il faut ajouter une fonction asTransitiveGraph dans Preference

2019-06-24 10:17 UTC, oliviercailloux requested changes
Vous ne respectez pas le contrat de `asGraph()`.

Dans ce cas, vous pouvez vous en sortir avec un seul graphe, transitivement fermé. (Si on veut maintenir les deux structures, comme dans un cas d’obtention d’informations de façon interactive et incrémentale, on utilisera plutôt une structure permettant les mutations.)

Votre constructeur doit être plus général. En l’état, il n’est possible que de créer une préférence qui serait complète. Ce n’est pas le contrat de cette classe (et cela dupliquerait une classe existante qui fait déjà ça). 

Il faut accepter en entrée un Graph<Alternative> représentant une relation de préférence partielle “at least as good as”, dont vous calculez vous-même la fermeture transitive (comme vous le faites pour le moment).

2019-06-24 11:37 UTC, ErnestBidouille commented
@oliviercailloux J'ai fais les changements demandés. Je créerai la fonction dans Preference lors d'une prochaine PR

2019-06-24 15:59 UTC, oliviercailloux requested changes

2019-06-24 15:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    public static ImmutablePreference asImmutablePreference(Voter voter,
Celui-ci est le constructeur bizarre qu’on utilisera moins souvent, il mérite donc un nom plus bizarre, pour laisser la plus grande visibilité au constructeur le plus sûrement utile. `fromSetOfPairs` conviendrait par exemple.

Notez que je reste sceptique sur l’utilité de ce constructeur, qui de plus manque d’élégance. Votre `List<Alternative>` représente en réalité ici une paire d’alternatives, si je comprends bien, ce qui est bizarre (l’utilisateur s’attend à pouvoir mettre un nombre variable d’alternatives dans une liste !). Donc votre `Set<List<Alternative>>` représente en réalité un ensemble de paires, c-à-d un graphe ! Pourquoi ne pas utiliser une structure appropriée (un graphe) dans ce cas, et inviter votre utilisateur à faire de même ?

Si vous tenez à le laisser, je ne vous en empêche pas, au moins votre implémentation semble correcte. Mais sachez qu’une bonne conception requiert souvent d’avoir la force d’effacer du code, même quand on l’a écrit avec beaucoup d’amour.

2019-06-24 15:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    public static ImmutablePreference graphToImmutablePreferenceImpl(
`asImmutablePreference`

2019-06-24 15:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    private ImmutablePreferenceImpl(Voter voter, Graph<Alternative> graph) {
Pas facile de lire et vérifier les garanties de cette classe avec ces deux constructeurs, qui de plus copient du code entre eux (cf. BP local design), et dans l’état actuel les vérifications copiées dans deux méthodes (donc si on en oublie dans une des deux, la garantie ne tient plus).

Mieux vaudrait un seul constructeur privé (conservez le plus élégant, celui qui accepte un graphe), et créer le graphe dans `fromSetOfPairs`.

2019-06-24 16:55 UTC, ErnestBidouille commented
@oliviercailloux je verrais bien une fonction fromMutablePreference(MutablePreference mutablePref) par la suite lorsque celle-ci sera implantée. Qu'en pensez-vous ?

2019-06-24 17:07 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    public static ImmutablePreference asImmutablePreference(Voter voter,
@oliviercailloux malgré le fait que je lui trouvais un certain intérêt (possibilité de créer une préférence depuis un ensemble de comparaisons), j'ai préféré l'enlever

2019-06-24 17:09 UTC, ErnestBidouille commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    private ImmutablePreferenceImpl(Voter voter, Graph<Alternative> graph) {
@oliviercailloux je n'ai pas compris "créer le graphe dans fromSetOfPairs". Cette fonction est-elle vraiment nécessaire ?

2019-06-24 17:31 UTC, ErnestBidouille commented
@oliviercailloux j'ai ajouté une obligation de graphe orienté dans la Factory. Ce test d'escape rapide était indispensable selon moi

2019-06-25 07:59 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    private ImmutablePreferenceImpl(Voter voter, Graph<Alternative> graph) {
Non, j’écrivais ceci dans l’optique où vous souhaitiez le conserver.

2019-06-25 08:13 UTC, oliviercailloux commented
> @oliviercailloux je verrais bien une fonction "fromMutablePreference(mutablePref : MutablePreference) : ImmutablePreference" par la suite lorsque celle-ci sera implantée. Qu'en pensez-vous ?

Oui, l’idée est bonne. Mais il faudrait être plus général : `fromPreference(preference: Preference)`.

2019-06-25 08:14 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    public static ImmutablePreference asImmutablePreference(Voter voter,
On peut créer une préférence depuis un ensemble de comparaisons, en les mettant dans un graphe.

2019-06-25 08:36 UTC, oliviercailloux requested changes

2019-06-25 08:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +    private Graph<Alternative> createGraph(Graph<Alternative> graph) {
Voilà un nom pas explicite. Par exemple, `toReflexiveGraph` conviendrait. (Mais je pense que cette méthode ne sert à rien.)

2019-06-25 08:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +        tmpGraph.isDirected();
Ne sert à rien.

2019-06-25 08:36 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImpl.java
> +                        .copyOf(createGraph(graph));
Je ne vois pas de raison d’ajouter les boucles réflexives dans le graphe, puisqu’on n’ajoute pas non plus les arcs par transitivité. Le graphe non transitif représente l’information telle que fournie, sans transformation.

2019-06-26 08:03 UTC, oliviercailloux commented
> > @oliviercailloux je verrais bien une fonction "fromMutablePreference(mutablePref : MutablePreference) : ImmutablePreference" par la suite lorsque celle-ci sera implantée. Qu'en pensez-vous ?
> 
> Oui, l’idée est bonne. Mais il faudrait être plus général : `fromPreference(preference: Preference)`.

Mieux : `copyOf(preference)`, par cohérence avec Guava. (Bonus : réfléchissez aux optimisations simples que vous pouvez utiliser.)

2019-06-26 08:11 UTC, oliviercailloux approved these changes

2019-06-26 08:11 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImplTest.java
> +        assertTrue(toTestImmutableGraph.hasEdgeConnecting(Alternative.withId(4),
Un peu pénible à lire. Considérez définir des champs statiques `a1`, `a2`, etc. (initialisés dès leur déclaration) pour augmenter la lisibilité. Voire même `a12`, (`ImmutableSet`), etc., pour les ensembles dont vous avez besoin.

Mieux encore : prévoir une classe (dans la partie Test), nommée `AlternativeHelper` par exemple, qui contient toutes ces définitions dans des champs statiques, pour 5 alternatives. Ce test ferait des imports statiques et utiliserait ces définitions.

Facultatif.

2019-06-26 12:47 UTC, ErnestBidouille commented
>
>  (Bonus : réfléchissez aux optimisations simples que vous pouvez utiliser.)

@oliviercailloux j'ai du mal à voir ce que vous entendez par optimisations simples

2019-06-26 12:55 UTC, ErnestBidouille commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutablePreferenceImplTest.java
> +        assertTrue(toTestImmutableGraph.hasEdgeConnecting(Alternative.withId(4),
@oliviercailloux DONE. 
AlternativeHelper sera implementée davantage dans une autre PR

2019-06-26 13:03 UTC, merged