ImmutableAntiSymmetric
j-voting/J-Voting pull request #42
Opened 2019-06-24 18:24 UTC by ErnestBidouille

Done :
- ImmutableAntiSymmetricImpl
- ImmutableAntiSymmetricTest

2019-06-25 08:52 UTC, oliviercailloux requested changes
Scinder le test proposé en deux. Un test qui vérifie qu’une boucle réflexive (a, a) est interdite, un qui vérifie qu’une indifférence est interdite (a, b), (b, a).

2019-06-25 08:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/classes/ImmutableAntiSymmetricPreferenceImpl.java
> +                                "Two Alternatives can't be equals");
… can’t be ranked ex-æquo

2019-06-25 20:36 UTC, ErnestBidouille commented
@oliviercailloux Un test qui vérifie qu’une boucle réflexive (a, a) est interdite. Ce test est potentiellement très couteux en ressources. En effet il équivaut à rechercher l'existence d'un chemin allant du point a au point a pour chaque a=1..n. On part là sur une complexité potentielle égale à o(n^3). Souhaitez-vous vraiment qu'il soit implémenté malgré tout ?

2019-06-25 20:48 UTC, ErnestBidouille commented
@oliviercailloux les changements ont été appliqués

2019-06-26 08:27 UTC, oliviercailloux approved these changes
Mon commentaire précédent était mal rédigé : les boucles réflexives devraient être permises et non interdites. Heureusement, vous l’avez correctement interprété.

Facultatif : ajouter un test unitaire qui vérifie que la structure résultante est correcte quand il n’y a pas de boucle de taille 2 mais qu’il y a une boucle de taille 1 (donc une boucle réflexive).

2019-06-26 13:03 UTC, ErnestBidouille commented
@oliviercailloux DONE.

2019-06-26 13:09 UTC, merged