Mutable preference it4
j-voting/J-Voting pull request #43
Opened 2019-06-25 21:48 UTC by anaeldray

Nous n'avons pas très bien compris ce que vous entendez par "réfléchissez au respect du contrat par votre implémentation " lorsque vous parlez de la méthode getAlternatives dans la PR n° 34.

2019-06-25 21:59 UTC, ErnestBidouille commented
@j-voting/melta-jvoting vous avez remarqué qu'il y a deux classes de test ? MutablePreferenceImplTest et TestMutablePreferenceImpl

2019-06-26 10:02 UTC, oliviercailloux requested changes
Votre contrat est indiqué par la Javadoc. L’implémentation que j’ai vue ne respecte pas ce contrat. Voyez-vous pourquoi ? Si non, expliquez-moi brièvement comment vous comprenez le contrat.

2019-06-27 11:15 UTC, oliviercailloux requested changes
Conflits.

2019-06-30 09:40 UTC, emiliechhean commented
@oliviercailloux @anaeldray C'est de cette Pull Request dont je parle dans le commentaire de la PR #34 .

2019-06-30 09:41 UTC, oliviercailloux approved these changes
Il me semble que mes commentaires mis par erreur sur la PR #34 s’appliquent pour l’essentiel également sur cette PR. Je maintiens donc ma conclusion : à ce stade j’accepte cette PR en l’état. Fusionner après éventuelles adaptations mineures comme demandé en PR #34.

2019-06-30 09:41 UTC, oliviercailloux commented
Dites-moi s’il y a des différences importantes entre cette PR et la PR #34 qui m’auraient échappées.

2019-06-30 09:54 UTC, emiliechhean commented
@oliviercailloux Les différences sont quand même assez importantes, étant donné que nous avons revu le constructeur, enlevé preferenceGraphMaker(), utilisé la classe AlternativeHelper et effectué un certain nombre de modifications. De plus, les modifications à faire que vous avez mentionné dans la PR #34 ont déjà été établies sur cette PR.

2019-06-30 11:02 UTC, oliviercailloux approved these changes
La méthode asGraph() devrait retourner un graphe qui reflète à tout moment la préférence, pas une copie immuable. Et l’ensemble des alternatives retourné devrait être une vue non modifiable (en l’état, vous vérifiez uniquement à l’appel de la méthode, c’est surprenant et peut introduire des bugs très difficiles à élucider). Mais à ce stade j’accepte cette PR en l’état. Fusionner après éventuelles adaptations mineures comme demandé.

2019-06-30 11:02 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/Preference.java
> +	 * @return <code>Voter</code> instance of the preference Returns the voter 0 if
C’était mieux avec une virgule.

2019-06-30 11:02 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/AlternativeHelper.java
> +    public static ImmutableSet<Alternative> a34 = ImmutableSet.of(a3, a4);
Facultatif : Tant que vous y étiez, vous auriez pu faire les 20 combinaisons de paires possibles et on aurait été tranquille ; et même ajouter cinq variables `a1Singleton`, `a2Singleton`, …

2019-06-30 11:02 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/j_voting/preferences/MutablePreferenceImplTest.java
> +        assertEquals(pref, pref1);
Facultatif : C’est vraiment un test très minimaliste ! Si on veut vraiment tester la copie, mieux vaudrait fournir une préférence non vide, et même de préférence un peu complexe, en entrée, pour vérifier si la copie a bien lieu. Mais ceci ne me semble pas indispensable vu les autres tests proposés. Vous pourriez simplement renommer ce test : `testGivenEmptyPref` (et supprimer le commentaire).

2019-06-30 11:02 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutablePreference.java
> +	public void putEdge(Alternative a1, Alternative a2);
Ceci n’est pas dans le diagramme, n’est-ce pas ? Je ne vois pas de raison forte de l’ajouter, car on peut tout aussi bien appeler `asMutableGraph().putEdge`. Mais votre idée n’est pas mauvaise s’il s’agit de simplifier l’usage pour le client, auquel cas il vaut mieux en profiter pour donner à cette méthode un nom plus parlant, c-à-d un nom en termes de préférences, que son équivalent abstrait en terme de graphe, par exemple, `setAtLeastAsGood`. (Facultatif : l’ajouter au diagramme.)

2019-06-30 12:52 UTC, emiliechhean commented on src/main/java/io/github/oliviercailloux/j_voting/preferences/interfaces/MutablePreference.java
> +	public void putEdge(Alternative a1, Alternative a2);
@oliviercailloux La méthode putEdge est bien dans le diagramme, mais je vais faire les modifications nécessaires.

2019-06-30 14:38 UTC, merged